# Generated by Django 2.1.1 on 2018-09-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='Imdb_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='Year',
        ),
    ]
