# Generated by Django 2.1.1 on 2018-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieList', '0003_movie_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='Imdb_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
