# Generated by Django 2.1.1 on 2018-09-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieList', '0004_auto_20180905_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Imdb_id',
            new_name='imdbID',
        ),
    ]
